apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-gitops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-gitops-demo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: aks-gitops-demo
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
      containers:
      - name: aks-gitops-demo
        image: kodekloud/webapp-color
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: APP_COLOR
          value: blue
        resources:
          requests:
            memory: "50Mi"
            cpu: "125m"
          limits:
            memory: "256Mi"
            cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: aks-gitops-demo
  labels:
    name: aks-gitops-demo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: aks-gitops-demo
